#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-requests
Version  : 2.21.0
Release  : 71
URL      : https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz
Summary  : Python HTTP for Humans.
Group    : Development/Tools
License  : Apache-2.0
Requires: deprecated-requests-license = %{version}-%{release}
Requires: deprecated-requests-python = %{version}-%{release}
Requires: PySocks
Requires: certifi
Requires: chardet
Requires: idna
Requires: urllib3
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : setuptools
BuildRequires : setuptools-legacypython

%description
Requests: HTTP for Humansâ¢
==========================
[![image](https://img.shields.io/pypi/v/requests.svg)](https://pypi.org/project/requests/)
[![image](https://img.shields.io/pypi/l/requests.svg)](https://pypi.org/project/requests/)
[![image](https://img.shields.io/pypi/pyversions/requests.svg)](https://pypi.org/project/requests/)
[![codecov.io](https://codecov.io/github/requests/requests/coverage.svg?branch=master)](https://codecov.io/github/requests/requests)
[![image](https://img.shields.io/github/contributors/requests/requests.svg)](https://github.com/requests/requests/graphs/contributors)
[![image](https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg)](https://saythanks.io/to/kennethreitz)

%package legacypython
Summary: legacypython components for the deprecated-requests package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-requests package.


%package license
Summary: license components for the deprecated-requests package.
Group: Default

%description license
license components for the deprecated-requests package.


%package python
Summary: python components for the deprecated-requests package.
Group: Default

%description python
python components for the deprecated-requests package.


%prep
%setup -q -n requests-2.21.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554327833
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python test_requests.py || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-requests
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-requests/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-requests/LICENSE

%files python
%defattr(-,root,root,-)
